chat/urls.py
from django.conf.urls import url,include


from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name='chat'


urlpatterns = [
	
    url(r'^$', views.index, name='index'),
    
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
	url(r'^accounts/', include('allauth.urls')),
	url(r'^classroom/',include('classroom.urls')),
    url(r'^taskapp/',include('taskapp.urls')),
    url(r'^chat/',include('chat.urls')),
    url(r'^admin/', admin.site.urls),

]

taskapp/urls.py
from django.conf.urls import url,include


from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name='taskapp'


urlpatterns = [
	url(r'^accounts/', include('allauth.urls')),
    url(r'^$', views.home, name='home'),
    url(r'^tasks/$',views.tasks,name='tasks'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^addtask/$',views.addtask,name='addtask'),
    url(r'^complete/(?P<taskid>\d+)/$',views.complete,name='complete'),
    url(r'^incomplete/(?P<taskid>\d+)/$',views.incomplete,name='incomplete'),
    url(r'^edittask/(?P<taskid>\d+)/$',views.edittask,name='edittask'),
    url(r'^moveup/(?P<prid>\d+)/$',views.moveup,name='moveup'),
    url(r'^movedown/(?P<prid>\d+)/$',views.movedown,name='movedown')
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taskapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.db import models
# from django.dispatch import receiver
# from django.db.models.signals import post_save

from django.conf import settings
import datetime
# from .utils import new_key,totp
import binascii
import time
from django.conf import settings
from django.db import models

# Create your models here.




class usertask(models.Model):				#migrate gives error sometimes due to migrations file not match jaise agar makemigration kiya but migrate nhi
											# aise ma migrations file delete karke firse makemigratns and migrate karo

	id=models.AutoField(primary_key=True)
	content=models.CharField(max_length=300)
	pub_date=models.DateTimeField('date created',auto_now_add=True)
	priority=models.IntegerField(default=0)
	complete=models.BooleanField(default=False)
	upload=models.FileField(upload_to='upload/')
	owner = models.ForeignKey(User,on_delete=models.CASCADE)

taskapp/views.py
from django.shortcuts import render


# Create your views here.

from django.shortcuts import render
from django.shortcuts import render,redirect

from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse

from django.db.models import F
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
import datetime
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm, UserCreationForm
from django.contrib.auth import update_session_auth_hash, login, authenticate
from django.contrib import messages
from django.shortcuts import render, redirect
from social_django.models import UserSocialAuth

from django.forms import ModelForm
from .models import usertask


from django import forms
from django.core.exceptions import ValidationError

from django.conf import settings
from django_popup_view_field.registry import registry_popup_view
from django.views.generic import TemplateView


from allauth.account.forms import SignupForm


# Create your views here.


class addtaskform(ModelForm):
	class Meta:
		model=usertask
		fields=['content','upload']

class edittaskform(forms.Form):
	newcontent=forms.CharField(max_length=300)



def home(request):
	return render(request,'taskapp/home.html')

@login_required
def profile(request):
	user=request.user;
	context={'user':user}
	return render(request,'taskapp/profile.html',context)

@login_required
def addtask(request):
	
	user=request.user
	complete=usertask.objects.filter(owner=user,complete=True).order_by('-priority')
	incomplete=usertask.objects.filter(owner=user,complete=False).order_by('-priority')

	if request.method=='POST':
		form=addtaskform(request.POST,request.FILES)

		if form.is_valid():
			
			content=form.cleaned_data['content']
			pic=form.cleaned_data['upload']
			newtask=usertask(content=content,owner=request.user,upload=pic)
			# uid=newtask.id // GIVES NONE
			newtask.save()
			newtask.priority=newtask.id 
			newtask.save()
						#id is allotedonly after save not create *
			
			return redirect('taskapp:addtask')

		else:
			return redirect('taskapp:addtask')
	else:
		form=addtaskform()
		return render(request,'taskapp/addtask.html',{'user':user,'complete':complete,'incomplete':incomplete,'form':form})

@login_required
def tasks(request):
	user=request.user
	
	complete=usertask.objects.filter(owner=user,complete=True).order_by('-priority')
	incomplete=usertask.objects.filter(owner=user,complete=False).order_by('-priority')
	
	#context={'user':user,'complete':complete,'incomplete':incomplete,'form':form}

	if request.method=='POST':
		form2=addtaskform(request.POST,request.FILES)
		form1=edittaskform()
		if form2.is_valid():
			
			content=form2.cleaned_data['content']
			pic=form2.cleaned_data['upload']
			newtask=usertask(content=content,owner=request.user,upload=pic)
			# uid=newtask.id // GIVES NONE
			newtask.save()
			newtask.priority=newtask.id 
			newtask.save()

			return redirect('taskapp:tasks')
		else:
			form2=addtaskform(request.POST,request.FILES)
			form1=edittaskform()
			return redirect('taskapp:tasks')
	
	
	form2=addtaskform()
	form1=edittaskform()
	return render(request,'taskapp/tasks.html',{'form2':form2,'user':user,'complete':complete,'incomplete':incomplete,'form1':form1})			

	#return render(request,'taskapp/tasks.html',context)
	
def moveup(request,prid):
	task=usertask.objects.get(priority=prid)
	
	task2=usertask.objects.get(priority=int(prid)+1)
	temp=task2.priority
	task2.priority=task.priority
	task.priority=temp
	task.save()
	task2.save()
	return HttpResponseRedirect(reverse('taskapp:addtask'))

def movedown(request,prid):
	task=usertask.objects.get(priority=prid)
	task2=usertask.objects.get(priority=int(prid)-1)
	temp=task2.priority
	task2.priority=task.priority
	task.priority=temp
	task.save()
	task2.save()
	return HttpResponseRedirect(reverse('taskapp:addtask'))


def complete(request,taskid):
	task=usertask.objects.get(id=taskid)
	task.complete=True
	task.save()
	return HttpResponseRedirect(reverse('taskapp:addtask'))


def incomplete(request,taskid):
	task=usertask.objects.get(id=taskid)
	task.complete=False
	task.save()
	return HttpResponseRedirect(reverse('taskapp:addtask'))

def edittask(request,taskid):
	if request.method=='POST':
		form=edittaskform(request.POST)

		if form.is_valid():
			
			newcontent=form.cleaned_data['newcontent']
			task=usertask.objects.get(id=taskid)
			task.content=newcontent
			task.save()
			return redirect('taskapp:tasks')

		else:
			return redirect('taskapp:tasks')
	else:
		form=edittaskform()
		return render(request,'taskapp/tasks.html',{'form':form})

taskapp/templates/taskapp/home.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title></title>

	<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">


</head>
<body>

<div class="container">

 <ul>
    
        <li><a >hbjhhjghftfg</a></li>
    
    </ul>


<img src="{% static 'polls/images/newimage.png' %}">
</div>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:details' question.id %}">{{ question.question_text }} {{ question.id}}  {{ question.pub_date}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}


</body>
</html>

taskapp/templates/taskapp/profile.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title></title>

 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


	<link rel="stylesheet" type="text/css" href="{% static 'taskapp/style2.css' %}">
</head>
<body>

<h1>hello {{ user.username }}</h1>

<h3>welcome to your profile</h3>
<div><a href="{% url 'taskapp:addtask' %}">Add new task</a></div>
<br><br>
<div><a href="{% url 'account_login' %}"> logout</a></div>



<div class="container">
  <h2>Modal Example</h2>
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <p>Some text in the modal.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>




</body>
</html>

taskapp/templates/taskapp/signup.html
<!DOCTYPE html>
<html>
<head>
	<title>signup</title>
</head>
<body>


  <form method="POST" action="/taskapp/signup">
    {% csrf_token %}
    {{ form.as_p }}
    <!-- {{ profile_form.as_p}} -->
    <button type="submit">Sign up</button>
  </form>


</div>

</body>
</html>

taskapp/templates/taskapp/tasks2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src='//production-assets.codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js'></script>
<!-- <script src='//production-assets.codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js'></script> -->
<script src='//production-assets.codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js'></script>
<meta charset='UTF-8'>
<meta name="robots" content="noindex">
<link rel="shortcut icon" type="image/x-icon" href="//production-assets.codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico" />
<link rel="mask-icon" type="" href="//production-assets.codepen.io/assets/favicon/logo-pin-f2d2b6d2c61838f7e76325261b7195c27224080bc099486ddd6dccb469b8e8e6.svg" color="#111" />
<link rel="canonical" href="https://codepen.io/dishantsoni/pen/pgVeQW?limit=all&page=46&q=draggable" />
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" >
    
<title></title>
</head>
<body>

<link rel="stylesheet" type="text/css" href="{% static 'taskapp/mytasks.css' %}">

<h1>hello  {{ user.username}}</h1>

<h3>here are your tasks</h3>

<!-- <h1>INCOMPLETE</h1>

{% for eachtask in complete %}

<h3>{{ eachtask.content}} -- dqdd -- pr {{ eachtask.priority}} --  id {{  eachtask.id}} -- <a href="{% url 'taskapp:movedown' eachtask.priority %}"> <span class="glyphicon glyphicon-chevron-down"></span></a> 
<a href="{% url 'taskapp:moveup' eachtask.priority %}"> <span class="glyphicon glyphicon-chevron-up"></span></a>
<a href="{% url 'taskapp:complete' eachtask.id %}"> <span class="	glyphicon glyphicon-ok"></span></a>  </h3>
<div><a href="{{ eachtask.upload.url }}">{{ eachtask.upload }}</a></div>
<div><img src="{{ eachtask.upload.url }}"></div>
{% endfor %}




<h1>COMPLETE</h1>


{% for eachtask in incomplete %}

<h3>{{ eachtask.content}} -- dqdd -- {{ eachtask.priority}} --  {{  eachtask.id}} -- </h3>

{% endfor %} -->

<header class="page-title">
<h1>  <i class="material-icons"></i>
TODO</h1>

<section class="todo-list-container">
<div class="todo-in-progress">
<h2> Working tasks</h2>
<ul ondragstart="" class="todo-list" id="target">

{% for eachtask in complete %}

<li draggable="true" class="todo-item high">
<div class="card">

<h3 class="todo-title"> 
<span class="action">
<i class="material-icons md-36 icon-delete">delete</i>
<a href="{% url 'taskapp:complete' eachtask.id %}"> <span class="	glyphicon glyphicon-ok"></span></a> 
<i class="icon-checkbox-outline material-icons md-36 md-dark">check_box_outline_blank</i>
<i class="icon-checkbox material-icons md-36 md-light">check_box</i>
</span> 
<span class="title">Learn React </span></h3>

<p class="todo-description">

Build great modularize javascript apps with React JS. </p>
<span class="todo-priority"> High </span>



</div>

</li>
{% endfor %}


<li class="todo-item new">
<div class="card">

<h3 class="todo-title"> <span class="action">
<i class="complete material-icons md-36 md-light">add_circle_outline</i>
</span> 
<a class="title" href="#">ADD A TODO</a></h3>

</div>

</li>


</ul>
</div>
</section>

<div class="todo-completed">
	<ul class="todo-list-completed">
		<h2> Completed Tasks </h2>
			<li class="todo-item high">
				<div class="icon-check">
					<i class="pad-15 material-icons md-36 md-light">check_circle</i>
				</div>

				<div class="icon-delete">
				<i class="pad-15 material-icons md-36 md-light">delete</i>
				</div>

				<div class="content">
				Learn React
				</div>
			</li>

			<li class="todo-item medium">
			<div class="icon-check">
			<i class="pad-15 material-icons md-36 md-light">check_circle</i>
			</div>
			<div class="icon-delete">
			<i class="pad-15 material-icons md-36 md-light">delete</i>
			</div>
			<div class="content">
			Learn React
			</div>
			</li>


			{% for eachtask in incomplete %}
			<li class="todo-item high">
				<div class="icon-check ">
					<i class="pad-15 material-icons md-36 md-light">check_circle</i>
				</div>

				<div class="icon-delete">
				<i class="pad-15 material-icons md-36 md-light">delete</i>
				</div>

				<div class="content">
				<h3>{{ eachtask.content}} -- dqdd -- {{ eachtask.priority}} --  {{  eachtask.id}} -- </h3>
				</div>
			</li>


		{% endfor %}

	</ul>

</div>


<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>


<!-- <!DOCTYPE html>
<html>
<head>
<title></title>
</head>
<body>

<form enctype="multipart/form-data" method="POST" >
{% csrf_token %}
{{ form.as_p }}
{{ profile_form.as_p}} -->
<!--<button type="submit">upload</button>

</form>

</body>
</html> -->