chat/urls.py
from django.conf.urls import url,include


from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name='chat'


urlpatterns = [
	
    url(r'^$', views.index, name='index'),
    
]

classroom/urls.py
from django.conf.urls import url

from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name='classroom'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^newdoubt/$',views.newdoubt,name='newdoubt'),
    url(r'^alldoubts/$',views.alldoubts,name='alldoubts'),
    url(r'^allassignments/$',views.allassignments,name='allassignments'),
    url(r'^addassignment/$',views.addassignment,name='addassignment'),
    url(r'^allnotices/$',views.allnotices,name='allnotices'),
    url(r'^moreuserinfo/$',views.moreuserinfo,name='moreuserinfo'),
    # url(r'^signup/$',views.signup,name='signup'),
    # url(r'^commenttry/$',views.commenttry,name='commenttry'),
    # url(r'^allcomments/$',views.allcomments,name='allcomments'),
   
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
	url(r'^accounts/', include('allauth.urls')),
	url(r'^classroom/',include('classroom.urls')),
    url(r'^taskapp/',include('taskapp.urls')),
    url(r'^chat/',include('chat.urls')),
    url(r'^admin/', admin.site.urls),

]

classroom/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


# class UserProfile(models.Model):
# 	user=models.OneToOneField(User,unique=True,related_name='profile',on_delete=models.CASCADE)
# 	dob=models.DateField()


class userMoreInfo(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	dob = models.DateField()
	choices=[(1,u'Teacher'),(2,u'Student'),]
	designation=models.CharField(max_length=10, choices=choices)
	profilephoto=models.FileField(upload_to='upload/')
    
class doubt(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	id=models.AutoField(primary_key=True)
	question=models.TextField(null=False)
	subject=models.CharField(max_length=30,null=False)
	time=models.DateTimeField(auto_now_add=True)

class reply(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	content=models.TextField()
	par_id=models.ForeignKey(doubt,on_delete=models.CASCADE)
	time=models.DateTimeField(auto_now_add=True)

class assignment(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	subject=models.CharField(max_length=30,null=False)
	time=models.DateTimeField(auto_now_add=True)
	upload=models.FileField(upload_to='upload/')
	complete=models.BooleanField(default=False)


class notice(models.Model):
	title=models.CharField(max_length=30,default="no title")
	content=models.TextField(null=True,blank=True)
	time=models.DateTimeField(auto_now_add=True)

classroom/forms.py
from django import forms
from .models import doubt,reply,assignment,notice,userMoreInfo
from datetime import datetime
# from django.db import models
# from django.forms import ModelForm


date_range = 50    
this_year = datetime.now().year

# class SignupForm(forms.ModelForm):
#     dob = forms.DateField(label='Date of Birth',widget=forms.SelectDateWidget(years=range(this_year - date_range, this_year + date_range)))
#     designation=forms.ChoiceField(choices=[
#     	(1,u'Teacher'),
#     	(2,u'student'),])

#     def signup(self, request, user):
#         user.dob = self.cleaned_data['dob']
#         user.designation = self.cleaned_data['designation']
#         user.save()

#     class Meta:
#         model = UserProfile
#         fields=['dob']


class userMoreInfoForm(forms.Form):

    dob=forms.DateField(label='Date of Birth',widget=forms.SelectDateWidget(years=range(this_year - date_range, this_year + date_range)))
    designation=forms.ChoiceField(choices=[
      (1,u'Teacher'),
      (2,u'student'),])



         

class adddoubtform(forms.ModelForm):

    class Meta:
        model=doubt
        fields=['question','subject',]
    


class replyform(forms.ModelForm):

    class Meta:
        model=reply
        fields=['content']
        labels={"content" : "reply"}

class addassignmentform(forms.ModelForm):

    class Meta:
        model=assignment
        fields=['subject','upload']

class addnotice(forms.ModelForm):

    class Meta:
        model=notice
        fields=['title','content']
        

classroom/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import update_session_auth_hash, login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django import forms
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import ModelForm
from .models import doubt,reply,assignment,notice,userMoreInfo
from .forms import addassignmentform,userMoreInfoForm, adddoubtform,replyform,addnotice
from allauth.account.adapter import DefaultAccountAdapter

# from django.core.cache import cache
# cache.set('noofdoubts', 0)
# cache.set('noofreplies', 0)

# Create your views here. 



def index(request):
	notices=notice.objects.all()
	return render(request,'classroom/index.html',{'notices':notices})


@login_required
def profile(request):
	return render(request,'classroom/profile.html')

@login_required
def newdoubt(request):
	if request.method=='POST':
		form=adddoubtform(request.POST)
		if form.is_valid():
			#cache.incr('noofdoubts')
			newdoubt=form.save(commit=False)
			newdoubt.user=request.user
			newdoubt.save()	
			
			# question=form.cleaned_data['question']
			# subject=form.cleaned_data['subject']
			# newdoubt=doubt(subject=subject,user=request.user,question=question)
			# newdoubt.save()
						
			return redirect(reverse('classroom:alldoubts'))
		else:
			return render(request,'classroom/newdoubt.html',{'form':form})
	else:
		form=adddoubtform()
		return render(request,'classroom/newdoubtdoubt.html',{'form':form})

@login_required
def alldoubts(request):
	form=replyform(request.POST)
	doubts=doubt.objects.all()
	noofdoubts=doubt.objects.count()
	noofreplies=reply.objects.count()
	user=request.user
	return render(request,'classroom/alldoubts.html',{'form':form, 'doubts':doubts,'noofdoubts':noofdoubts,'noofreplies':noofreplies,'user':user})


def allassignments(request):
	assignments=assignment.objects.all()
	return render(request,'classroom/allassignments.html',{'assignments':assignments})

def addassignment(request):
	user=request.user
	
	if request.method=='POST':
		form=addassignmentform(request.POST,request.FILES)

		if form.is_valid():
			
			subject=form.cleaned_data['subject']
			pic=form.cleaned_data['upload']
			newassignment=assignment(subject=subject,user=request.user,upload=pic)
			newassignment.save()
			
			return redirect(reverse('classroom:allassignments'))

		else:
			return redirect(reverse('classroom:addassignment'))
	else:
		form=addassignmentform()
		return render(request,'classroom/addassignment.html',{'form':form})



def allnotices(request):
	notices=notice.objects.all().order_by('-time')
	if request.method=='POST':
		form=addnotice(request.POST)
		
		if form.is_valid():			
			content=form.cleaned_data['content']
			title=form.cleaned_data['title']
			newnotice=notice(content=content,title=title)
			newnotice.save()
			return redirect(reverse('classroom:allnotices'))
		else:
			return redirect(reverse('classroom:allnotices'))
	else:
		form=addnotice()
		return render(request,'classroom/allnotices.html',{'form':form,'notices':notices})

def moreuserinfo(request):

	if request.method=='POST':
		form=userMoreInfoForm(request.POST,request.FILES)
		if form.is_valid():
			dob=form.cleaned_data['dob']
			designation=form.cleaned_data['designation']
			# pic=form.cleaned_data['uprofilepic']
			user=request.user
			newuserinfo=userMoreInfo(dob=dob,designation=designation,user=user)
			newuserinfo.save()
						
			return render(request,'classroom/profile.html')
		else:
			return render(request,'classroom/moreuserinfo.html',{'form':form})
	else:
		form=userMoreInfoForm()
		return render(request,'classroom/moreuserinfo.html',{'form':form})

classroom/templates/classroom/addassignment.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>add a new assignment</h1>
<form role="form" enctype="multipart/form-data" method="POST" >
							{% csrf_token %}
							{{ form.as_p }}
							 
							<button type="submit" class="btn btn-primary btn-block">upload</button>
						</form>

</body>
</html>

classroom/templates/classroom/allassignments.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>dqded</h1>
{% for eachassignment in assignments %}
{{ eachassignment.subject }}

<div><a href="{{ eachassignment.upload.url }}">{{ eachassignment.upload }}</a></div>
<img src="{{ eachassignment.upload.url }}">
<br>
<div><img src="{{ eachassignment.upload.url }}"></div>
{% endfor %}

</body>
</html>

classroom/templates/classroom/allcomments.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<h1>these are all comments and their users </h1>
<br>
<br>

{% for eachcomm in comments %}


<h3>{{ eachcomm.user }}   </h3>
<hr>
<span>{{eachcomm.time|timesince }} minutes ago</span>
<br>
<h4>{{ eachcomm.content }}}</h4>
<br><br>
{% endfor %}

</body>
</html>

classroom/templates/classroom/allcomments2.html
<!-- <!DOCTYPE html>
<html>
<head>
<title></title>
</head>
<body>
<h1>wddwefeew</h1>
<br>
{% for eachcomm in comments %}
<h3>{{ eachcomm.content }}  time ----  {{ eachcomm.time }}</h3>
{% endfor %}
</body>
</html>
-->

<!------ Include the above in your HEAD tag ---------->


<!DOCTYPE html><html class=''>
<head>
<script src='//production-assets.codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js'></script>
<!-- <script src='//production-assets.codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js'></script> -->
<script src='//production-assets.codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js'></script>
<meta charset='UTF-8'>
<meta name="robots" content="noindex">
<link rel="shortcut icon" type="image/x-icon" href="//production-assets.codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico" />
<link rel="mask-icon" type="" href="//production-assets.codepen.io/assets/favicon/logo-pin-f2d2b6d2c61838f7e76325261b7195c27224080bc099486ddd6dccb469b8e8e6.svg" color="#111" />
<link rel="canonical" href="https://codepen.io/Creaticode/pen/ijExL" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!-- Fuentes de Google -->
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
<!-- Iconos -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">



<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>


<style class="cp-pen-styles">/**
* Oscuro: #283035
* Azul: #03658c
* Detalle: #c7cacb
* Fondo: #dee1e3
----------------------------------*/
* {
	margin: 0;
	padding: 0;
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	box-sizing: border-box;
}

a {
	color: #03658c;
	text-decoration: none;
}

ul {
list-style-type: none;
}

body {
font-family: 'Roboto', Arial, Helvetica, Sans-serif, Verdana;
background: #dee1e3;
}

/** ====================
* Lista de Comentarios
=======================*/
.comments-container {
margin: 60px auto 15px;
width: 768px;
}

.comments-container h1 {
font-size: 36px;
color: #283035;
font-weight: 400;
}

.comments-container h1 a {
font-size: 18px;
font-weight: 700;
}

.comments-list {
margin-top: 30px;
position: relative;
}

/**
* Lineas / Detalles
-----------------------*/
.comments-list:before {
content: '';
width: 2px;
height: 100%;
background: #c7cacb;
position: absolute;
left: 32px;
top: 0;
}

.comments-list:after {
content: '';
position: absolute;
background: #c7cacb;
bottom: 0;
left: 27px;
width: 7px;
height: 7px;
border: 3px solid #dee1e3;
-webkit-border-radius: 50%;
-moz-border-radius: 50%;
border-radius: 50%;
}

.reply-list:before, .reply-list:after {display: none;}
.reply-list li:before {
content: '';
width: 60px;
height: 2px;
background: #c7cacb;
position: absolute;
top: 25px;
left: -55px;
}


.comments-list li {
margin-bottom: 15px;
display: block;
position: relative;
}

.comments-list li:after {
content: '';
display: block;
clear: both;
height: 0;
width: 0;
}

.reply-list {
padding-left: 88px;
clear: both;
margin-top: 15px;
}
/**
* Avatar
---------------------------*/
.comments-list .comment-avatar {
width: 65px;
height: 65px;
position: relative;
z-index: 99;
float: left;
border: 3px solid #FFF;
-webkit-border-radius: 4px;
-moz-border-radius: 4px;
border-radius: 4px;
-webkit-box-shadow: 0 1px 2px rgba(0,0,0,0.2);
-moz-box-shadow: 0 1px 2px rgba(0,0,0,0.2);
box-shadow: 0 1px 2px rgba(0,0,0,0.2);
overflow: hidden;
}

.comments-list .comment-avatar img {
width: 100%;
height: 100%;
}

.reply-list .comment-avatar {
width: 50px;
height: 50px;
}

.comment-main-level:after {
content: '';
width: 0;
height: 0;
display: block;
clear: both;
}
/**
* Caja del Comentario
---------------------------*/
.comments-list .comment-box {
width: 680px;
float: right;
position: relative;
-webkit-box-shadow: 0 1px 1px rgba(0,0,0,0.15);
-moz-box-shadow: 0 1px 1px rgba(0,0,0,0.15);
box-shadow: 0 1px 1px rgba(0,0,0,0.15);
}

.comments-list .comment-box:before, .comments-list .comment-box:after {
content: '';
height: 0;
width: 0;
position: absolute;
display: block;
border-width: 10px 12px 10px 0;
border-style: solid;
border-color: transparent #FCFCFC;
top: 8px;
left: -11px;
}

.comments-list .comment-box:before {
border-width: 11px 13px 11px 0;
border-color: transparent rgba(0,0,0,0.05);
left: -12px;
}

.reply-list .comment-box {
width: 610px;
}
.comment-box .comment-head {
background: #FCFCFC;
padding: 10px 12px;
border-bottom: 1px solid #E5E5E5;
overflow: hidden;
-webkit-border-radius: 4px 4px 0 0;
-moz-border-radius: 4px 4px 0 0;
border-radius: 4px 4px 0 0;
}

.comment-box .comment-head i {
float: right;
margin-left: 14px;
position: relative;
top: 2px;
color: #A6A6A6;
cursor: pointer;
-webkit-transition: color 0.3s ease;
-o-transition: color 0.3s ease;
transition: color 0.3s ease;
}

.comment-box .comment-head i:hover {
color: #03658c;
}

.comment-box .comment-name {
color: #283035;
font-size: 14px;
font-weight: 700;
float: left;
margin-right: 10px;
}

.comment-box .comment-name a {
color: #283035;
}

.comment-box .comment-head span {
float: left;
color: #999;
font-size: 13px;
position: relative;
top: 1px;
}

.comment-box .comment-content {
background: #FFF;
padding: 12px;
font-size: 15px;
color: #595959;
-webkit-border-radius: 0 0 4px 4px;
-moz-border-radius: 0 0 4px 4px;
border-radius: 0 0 4px 4px;
}

.comment-box .comment-name.by-author, .comment-box .comment-name.by-author a {color: #03658c;}
.comment-box .comment-name.by-author:after {
content: 'autor';
background: #03658c;
color: #FFF;
font-size: 12px;
padding: 3px 5px;
font-weight: 700;
margin-left: 10px;
-webkit-border-radius: 3px;
-moz-border-radius: 3px;
border-radius: 3px;
}

/** =====================
* Responsive
========================*/
@media only screen and (max-width: 766px) {
.comments-container {
	width: 480px;
}

.comments-list .comment-box {
	width: 390px;
}

.reply-list .comment-box {
	width: 320px;
}
}</style></head><body>
<!-- Contenedor Principal -->
<div class="comments-container">
	<h1>Comentarios <a href="http://creaticode.com">creaticode.com</a></h1>

	<ul id="comments-list" class="comments-list">

			{% for eachcomm in comments %}

			<li>
			<div class="comment-main-level">
				<!-- Avatar -->
				<div class="comment-avatar"><img src="" alt="">
				</div>
				<!-- Contenedor del Comentario -->
				<div class="comment-box">
					<div class="comment-head">
						<h6 class="comment-name by-author"><a href="">{{ eachcomm.user }}</a></h6>
						<span>{{eachcomm.time|timesince }} minutes ago</span>
						<a class="comment-reply-btn" href="." ><i class="fa fa-reply"></i></a>
						<i class="fa fa-heart"></i>
					</div>
					<div class="comment-content">
						{{ eachcomm.content }}}
					</div>
					<footer> {{eachcomm.time}}</footer>
				</div>

			</div>
			
				<div class="comment-reply comments-list reply-list" style="display: none;">
			{% for eachreply in eachcomm.reply_set.all %}
				<li>

					<div class="comment-avatar"><img src="" alt=""></div>
					<!-- Contenedor del Comentario -->
					<div class="comment-box">
						<div class="comment-head">
							<h6 class="comment-name"><a href="">{{ reachreply.user }}</a></h6>
							<span>hace 10 minutos</span>
							<i class="fa fa-reply"></i>
							<i class="fa fa-heart"></i>
						</div>
						<div class="comment-content">
							{{ eachreply.content }}}
						</div>
					</div>
					<footer> {{eachreply.time }}</footer>


				</li>
			{% endfor %}
<h1>wewqeererrr</h1>

<form method="post" action="{% url 'classroom:postreply' eachcomm.obj_id %}">
{% csrf_token %}
{{ form.as_p }}
 <button type="submit">reply</button>
</form>

			</div>

		</li>

			{% endfor %}

	</ul>
</div>

<script>
$(document).ready(function(){
$(".comment-reply-btn").click(function(event){
event.preventDefault();

$(this).parent().parent().parent().next(".comment-reply").fadeToggle(); 
});
});

</script>
</body>


</html>

classroom/templates/classroom/commenttry.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<h1>comment</h1>

<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
     
    
    <button type="submit">submit</button>
  </form>



</body>
</html>

classroom/templates/classroom/doubts.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<h1>dasdsder</h1>


{% for eachdoubt in doubts %}
<h3>{{ eachdoubt.subject }}</h3>
{% endfor %}
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
     
    
    <button type="submit">submit</button>
  </form>


</body>
</html>

classroom/templates/classroom/index2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<style type="text/css">
  
  .carousel-container .item{
  max-height: 500px;
  }



</style>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <title> INDEX PAGE</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'classroom/index/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'classroom/index/css/scrolling-nav.css' %}" rel="stylesheet">





<body>

 <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">HELLO USER</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

<header class="bg-primary text-white">
      <div class="container text-center">
        <h1>Welcome to INDEX PAGE</h1>
        <p class="lead">A common forum for all things</p>
      </div>
    </header>


<div class="carousel-container">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

      <div class="item active">
        <img class="pic" src="https://ununsplash.imgix.net/photo-1416339134316-0e91dc9ded92?q=75&fm=jpg&s=883a422e10fc4149893984019f63c818" alt="Los Angeles" style="width:100%;">
        <div class="carousel-caption">
          <h3>Los Angeles</h3>
          <p>LA is always so much fun!</p>
        </div>
      </div>

      <div class="item">
        <img class="pic" src="https://ununsplash.imgix.net/photo-1416339684178-3a239570f315?q=75&fm=jpg&s=c39d9a3bf66d6566b9608a9f1f3765af" alt="Chicago" style="width:100%;">
        <div class="carousel-caption">
          <h3>Chicago</h3>
          <p>Thank you, Chicago!</p>
        </div>
      </div>
    
      <div class="item">
        <img class="pic"  src="https://ununsplash.imgix.net/photo-1416339276121-ba1dfa199912?q=75&fm=jpg&s=9bf9f2ef5be5cb5eee5255e7765cb327" alt="New York" style="width:100%;">
        <div class="carousel-caption">
          <h3>New York</h3>
          <p>We love the Big Apple!</p>
        </div>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  
</div>
</div>


<section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>About this page</h2>
            <p class="lead">This is a great place to talk about your webpage. This template is purposefully unstyled so you can use it as a boilerplate or starting point for you own landing page designs! This template features:</p>
            <ul>
              <li>Clickable nav links that smooth scroll to page sections</li>
              <li>Responsive behavior when clicking nav links perfect for a one page website</li>
              <li>Bootstrap's scrollspy feature which highlights which section of the page you're on in the navbar</li>
              <li>Minimal custom CSS so you are free to explore your own unique design options</li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <section id="services" class="bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>Services we offer</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore, expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda laborum vel, labore ut velit dignissimos.</p>
          </div>
        </div>
      </div>
    </section>

    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>Contact us</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'classroom/index/vendor/jquery/jquery.min.js' %} "></script>
    <script src="{% static 'classroom/index/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'classroom/index/vendor/jquery-easing/jquery.easing.min.js' %} "></script>

    <!-- Custom JavaScript for this theme -->
    <script src="{% static 'classroom/index/js/scrolling-nav.js' %} "></script>

</body>
</html>

classroom/templates/classroom/moreuserinfo.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form method="post" >
{% csrf_token %}
{{ form.as_p }}
 <button type="submit">Submit</button>
</form>
</body>
</html>

classroom/templates/classroom/profile.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<h1>welcome user </h1>



</body>
</html>

classroom/templates/classroom/signup.html
<!DOCTYPE html>
<html>
<head>
	<title>signup</title>
</head>
<body>

<form class="site-form"  method="POST">
	
	{<h2>Sign up</h2>
  <h3>qwdwqdnwkjdk</h3>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        <!-- {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %} -->
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
</form>




</body>
</html>